name: build
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  permissions:
    packages: write
    contents: read

  jobs:
    docker:
      runs-on: ubuntu-latest
      steps:

        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Login to Docker
          uses: docker/login-action@v3
          with:
            registry: ${{ vars.DOCKER_REGISTRY}}
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Get the tag name
          id: get_version
          run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: |
              ${{ vars.DOCKER_REGISTRY }}/pubquiz-bot:${{steps.get_version.outputs.VERSION}}
            
